package com.survey.vo;

import java.util.Date;


/**
 * TUmOrgan generated by MyEclipse Persistence Tools
 */

public class TUmOrganVO  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int umOrganId;
     private int parentId;
     private String fullName;
     private String abbrName;
     private String umOrgCode;
     private int orgLevel;
     private Integer orgType;
     private String zip;
     private String address;
     private String telephone;
     private String fax;
     private String status;
     private String organId;
     private String deptId;
     private Date insertTime;
     private Date updateTime;





    public int getParentId() {
		return parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	public int getUmOrganId() {
		return umOrganId;
	}

	public void setUmOrganId(int umOrganId) {
		this.umOrganId = umOrganId;
	}

	public void setOrgLevel(int orgLevel) {
		this.orgLevel = orgLevel;
	}

	public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getAbbrName() {
        return this.abbrName;
    }
    
    public void setAbbrName(String abbrName) {
        this.abbrName = abbrName;
    }

    public String getUmOrgCode() {
        return this.umOrgCode;
    }
    
    public void setUmOrgCode(String umOrgCode) {
        this.umOrgCode = umOrgCode;
    }

    public Integer getOrgLevel() {
        return this.orgLevel;
    }
    
    public void setOrgLevel(Integer orgLevel) {
        this.orgLevel = orgLevel;
    }

    public Integer getOrgType() {
        return this.orgType;
    }
    
    public void setOrgType(Integer orgType) {
        this.orgType = orgType;
    }

    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getOrganId() {
        return this.organId;
    }
    
    public void setOrganId(String organId) {
        this.organId = organId;
    }

    public String getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }

    public Date getInsertTime() {
        return this.insertTime;
    }
    
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
   








}