package com.ulic.ulweb.po;

import java.util.Date;

/**
 * UlContent generated by MyEclipse Persistence Tools
 */

public class UlContent implements java.io.Serializable {

	// Fields

	private Long contentId;

	private Long columnId;

	private String contentName;

	private String content;

	private Date uploadTime;

	private String uploadUser;

	private String organId;

	private Long isDelete;

	private Long attachmentSum;

	private String keyWord;

	private Date updateTime;

	private Long showOthersClass;

	private Long showOrganClass;

	private Long isQuickLink;

	private String documentNum;

	private String documentWord;

	private Date quickTime;

	private Long haveContent;

	private Long onIndex;

	private Long displayType;

	private Long quickTimeInt;

	private String subTitle;

	private String uploadDeptStr;

	private Long uploadDeptInt;

	// Constructors

	/** default constructor */
	public UlContent() {
	}

	/** minimal constructor */
	public UlContent(Long contentId) {
		this.contentId = contentId;
	}

	/** full constructor */
	public UlContent(Long contentId, Long columnId, String contentName,
			String content, Date uploadTime, String uploadUser, String organId,
			Long isDelete, Long attachmentSum, String keyWord, Date updateTime,
			Long showOthersClass, Long showOrganClass, Long isQuickLink,
			String documentNum, String documentWord, Date quickTime,
			Long haveContent, Long onIndex, Long displayType,
			Long quickTimeInt, String subTitle, String uploadDeptStr,
			Long uploadDeptInt) {
		this.contentId = contentId;
		this.columnId = columnId;
		this.contentName = contentName;
		this.content = content;
		this.uploadTime = uploadTime;
		this.uploadUser = uploadUser;
		this.organId = organId;
		this.isDelete = isDelete;
		this.attachmentSum = attachmentSum;
		this.keyWord = keyWord;
		this.updateTime = updateTime;
		this.showOthersClass = showOthersClass;
		this.showOrganClass = showOrganClass;
		this.isQuickLink = isQuickLink;
		this.documentNum = documentNum;
		this.documentWord = documentWord;
		this.quickTime = quickTime;
		this.haveContent = haveContent;
		this.onIndex = onIndex;
		this.displayType = displayType;
		this.quickTimeInt = quickTimeInt;
		this.subTitle = subTitle;
		this.uploadDeptStr = uploadDeptStr;
		this.uploadDeptInt = uploadDeptInt;
	}

	// Property accessors

	public Long getContentId() {
		return this.contentId;
	}

	public void setContentId(Long contentId) {
		this.contentId = contentId;
	}

	public Long getColumnId() {
		return this.columnId;
	}

	public void setColumnId(Long columnId) {
		this.columnId = columnId;
	}

	public String getContentName() {
		return this.contentName;
	}

	public void setContentName(String contentName) {
		this.contentName = contentName;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getUploadTime() {
		return this.uploadTime;
	}

	public void setUploadTime(Date uploadTime) {
		this.uploadTime = uploadTime;
	}

	public String getUploadUser() {
		return this.uploadUser;
	}

	public void setUploadUser(String uploadUser) {
		this.uploadUser = uploadUser;
	}

	public String getOrganId() {
		return this.organId;
	}

	public void setOrganId(String organId) {
		this.organId = organId;
	}

	public Long getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Long isDelete) {
		this.isDelete = isDelete;
	}

	public Long getAttachmentSum() {
		return this.attachmentSum;
	}

	public void setAttachmentSum(Long attachmentSum) {
		this.attachmentSum = attachmentSum;
	}

	public String getKeyWord() {
		return this.keyWord;
	}

	public void setKeyWord(String keyWord) {
		this.keyWord = keyWord;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Long getShowOthersClass() {
		return this.showOthersClass;
	}

	public void setShowOthersClass(Long showOthersClass) {
		this.showOthersClass = showOthersClass;
	}

	public Long getShowOrganClass() {
		return this.showOrganClass;
	}

	public void setShowOrganClass(Long showOrganClass) {
		this.showOrganClass = showOrganClass;
	}

	public Long getIsQuickLink() {
		return this.isQuickLink;
	}

	public void setIsQuickLink(Long isQuickLink) {
		this.isQuickLink = isQuickLink;
	}

	public String getDocumentNum() {
		return this.documentNum;
	}

	public void setDocumentNum(String documentNum) {
		this.documentNum = documentNum;
	}

	public String getDocumentWord() {
		return this.documentWord;
	}

	public void setDocumentWord(String documentWord) {
		this.documentWord = documentWord;
	}

	public Date getQuickTime() {
		return this.quickTime;
	}

	public void setQuickTime(Date quickTime) {
		this.quickTime = quickTime;
	}

	public Long getHaveContent() {
		return this.haveContent;
	}

	public void setHaveContent(Long haveContent) {
		this.haveContent = haveContent;
	}

	public Long getOnIndex() {
		return this.onIndex;
	}

	public void setOnIndex(Long onIndex) {
		this.onIndex = onIndex;
	}

	public Long getDisplayType() {
		return this.displayType;
	}

	public void setDisplayType(Long displayType) {
		this.displayType = displayType;
	}

	public Long getQuickTimeInt() {
		return this.quickTimeInt;
	}

	public void setQuickTimeInt(Long quickTimeInt) {
		this.quickTimeInt = quickTimeInt;
	}

	public String getSubTitle() {
		return this.subTitle;
	}

	public void setSubTitle(String subTitle) {
		this.subTitle = subTitle;
	}

	public String getUploadDeptStr() {
		return this.uploadDeptStr;
	}

	public void setUploadDeptStr(String uploadDeptStr) {
		this.uploadDeptStr = uploadDeptStr;
	}

	public Long getUploadDeptInt() {
		return this.uploadDeptInt;
	}

	public void setUploadDeptInt(Long uploadDeptInt) {
		this.uploadDeptInt = uploadDeptInt;
	}

}