package com.ulic.ulweb.po;

/**
 * UlColumn generated by MyEclipse Persistence Tools
 */

public class UlColumn implements java.io.Serializable {

	// Fields

	private int columnId;

	private String columnName;

	private String organId;

	private int columnLevel;

	private int parentId;

	private int isDelete;

	private int includeColumn;

	private int showToUser;

	private int includeContent;

	private int columnOrder;

	private int showOthersClass;

	private int showOrganClass;

	private int openColumn;

	private String columnEid;

	public String getColumnEid() {
		return columnEid;
	}

	public void setColumnEid(String columnEid) {
		this.columnEid = columnEid;
	}

	public int getColumnId() {
		return columnId;
	}

	public void setColumnId(int columnId) {
		this.columnId = columnId;
	}

	public int getColumnLevel() {
		return columnLevel;
	}

	public void setColumnLevel(int columnLevel) {
		this.columnLevel = columnLevel;
	}

	public String getColumnName() {
		return columnName;
	}

	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}

	public int getColumnOrder() {
		return columnOrder;
	}

	public void setColumnOrder(int columnOrder) {
		this.columnOrder = columnOrder;
	}

	public int getIncludeColumn() {
		return includeColumn;
	}

	public void setIncludeColumn(int includeColumn) {
		this.includeColumn = includeColumn;
	}

	public int getIncludeContent() {
		return includeContent;
	}

	public void setIncludeContent(int includeContent) {
		this.includeContent = includeContent;
	}

	public int getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(int isDelete) {
		this.isDelete = isDelete;
	}

	public int getOpenColumn() {
		return openColumn;
	}

	public void setOpenColumn(int openColumn) {
		this.openColumn = openColumn;
	}

	public String getOrganId() {
		return organId;
	}

	public void setOrganId(String organId) {
		this.organId = organId;
	}

	public int getParentId() {
		return parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	public int getShowOrganClass() {
		return showOrganClass;
	}

	public void setShowOrganClass(int showOrganClass) {
		this.showOrganClass = showOrganClass;
	}

	public int getShowOthersClass() {
		return showOthersClass;
	}

	public void setShowOthersClass(int showOthersClass) {
		this.showOthersClass = showOthersClass;
	}

	public int getShowToUser() {
		return showToUser;
	}

	public void setShowToUser(int showToUser) {
		this.showToUser = showToUser;
	}


}