package com.ulic.ulweb.po;

/**
 * UlOrgan generated by MyEclipse Persistence Tools
 */

public class UlOrgan implements java.io.Serializable {

	
	private int deptId;

	private String organId;

	private String organName;

	private int organModel;


	public int getDeptId() {
		return deptId;
	}

	public void setDeptId(int deptId) {
		this.deptId = deptId;
	}

	public String getOrganId() {
		return organId;
	}

	public void setOrganId(String organId) {
		this.organId = organId;
	}

	public int getOrganModel() {
		return organModel;
	}

	public void setOrganModel(int organModel) {
		this.organModel = organModel;
	}

	public String getOrganName() {
		return organName;
	}

	public void setOrganName(String organName) {
		this.organName = organName;
	}

}