package com.ulic.ulweb.po;

/**
 * UlRoleClass generated by MyEclipse Persistence Tools
 */

public class UlRoleClass implements java.io.Serializable {

	// Fields

	private int roleId;

	private int roleClass;

	private int isAdmin;

	private String columnId;

	private String organId;

	private String userName;

	public String getColumnId() {
		return columnId;
	}

	public void setColumnId(String columnId) {
		this.columnId = columnId;
	}

	public int getIsAdmin() {
		return isAdmin;
	}

	public void setIsAdmin(int isAdmin) {
		this.isAdmin = isAdmin;
	}

	public String getOrganId() {
		return organId;
	}

	public void setOrganId(String organId) {
		this.organId = organId;
	}

	public int getRoleClass() {
		return roleClass;
	}

	public void setRoleClass(int roleClass) {
		this.roleClass = roleClass;
	}

	public int getRoleId() {
		return roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}