package com.ulic.ulweb.ulweb2.entity;

import java.util.Date;

import com.ulic.ulweb.ulweb2.util.StatusMode;

// default package

/**
 * AttachmentEntity generated by MyEclipse Persistence Tools
 */

public class AttachmentEntity implements java.io.Serializable {

	// Fields

	private int attachmentId;

	private String attachmentPath;

	private int isDelete;

	private ContentEntity content;

	private String showName;

	private int attachmentOrder;

	private int attachmentType;

	private UlPolicy ulPolicy;

	private String uploadUser;

	private int status;

	private int needGenerate;

	private int needSecure;
	
	private Long clickNum;
	
	/**
	 * 出错信息
	 */
	private String errorMessage;
	
	/**
	 * paf文件的路径
	 */
	private String pdfPath;
	
	/**
	 * 加密文件的路径
	 */
	private String securePath;
	// Property accessors
	
	private Date updateTime;

	/**
	 * 此附件加密策略的名称
	 */
	private String policyName;

	public Long getClickNum() {
		return clickNum;
	}

	public void setClickNum(Long clickNum) {
		this.clickNum = clickNum;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public int getAttachmentId() {
		return this.attachmentId;
	}

	public void setAttachmentId(int attachmentId) {
		this.attachmentId = attachmentId;
	}

	public String getAttachmentPath() {
		return this.attachmentPath;
	}

	public void setAttachmentPath(String attachmentPath) {
		this.attachmentPath = attachmentPath;
	}

	public int getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(int isDelete) {
		this.isDelete = isDelete;
	}

	public String getShowName() {
		return this.showName;
	}

	public void setShowName(String showName) {
		this.showName = showName;
	}

	public int getAttachmentOrder() {
		return this.attachmentOrder;
	}

	public void setAttachmentOrder(int attachmentOrder) {
		this.attachmentOrder = attachmentOrder;
	}

	public int getAttachmentType() {
		return this.attachmentType;
	}

	public void setAttachmentType(int attachmentType) {
		this.attachmentType = attachmentType;
	}


	public UlPolicy getUlPolicy() {
		return ulPolicy;
	}

	public void setUlPolicy(UlPolicy ulPolicy) {
		this.ulPolicy = ulPolicy;
	}

	public String getUploadUser() {
		return this.uploadUser;
	}

	public void setUploadUser(String uploadUser) {
		this.uploadUser = uploadUser;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getNeedGenerate() {
		return this.needGenerate;
	}

	public void setNeedGenerate(int needGenerate) {
		this.needGenerate = needGenerate;
	}

	public int getNeedSecure() {
		return this.needSecure;
	}

	public void setNeedSecure(int needSecure) {
		this.needSecure = needSecure;
	}

	public String getErrorMessage() {
		return errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

	public String getPdfPath() {
		return pdfPath;
	}

	public void setPdfPath(String pdfPath) {
		this.pdfPath = pdfPath;
	}

	public String getSecurePath() {
		return securePath;
	}

	public void setSecurePath(String securePath) {
		this.securePath = securePath;
	}

	public String getPolicyName() {
		return policyName;
	}

	public void setPolicyName(String policyName) {
		this.policyName = policyName;
	}
	
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return "attachmentId: " + this.attachmentId + ", showName: "+ this.showName;
	}

	public ContentEntity getContent() {
		return content;
	}

	public void setContent(ContentEntity content) {
		this.content = content;
	}
	
	public String getStatusString() {
		return StatusMode.parse(status).toString();
	}
	
	/**
	 * 根据附件状态显示不同的文件真实路径
	 * @return
	 */
	public String getDisplayPath() {
		
		if (needSecure == 1 && status == 5 && securePath != null) {
			return securePath;
		} else if (needGenerate == 1 && status == 2 && pdfPath != null) {
			return pdfPath;
		} else if (needSecure == 0 && attachmentPath != null) {
			return attachmentPath;
		} else {
			return null;
		}
	}
	
	/**
	 * 根据附件状态判断是否允许删除附件
	 * @return
	 */
	public boolean getCanDelete() {
		
		if (status == 6 || status == 2 || status == -2 || status == 5 || status == -5) {
			return true;
		} else {
			return false;
		}
	}
	
}