package com.ulic.ulweb.ulweb2.entity;

import java.util.Date;

/**
 * UlAudit generated by MyEclipse Persistence Tools
 */

public class AuditEntity implements java.io.Serializable {

	private int accessId;

	private String ip;

	private Date accessTime;

	private String accessUrl;
	

	public AuditEntity() {
		super();
	}

	public AuditEntity(String ip, Date accessTime, String accessUrl) {
		super();
		this.ip = ip;
		this.accessTime = accessTime;
		this.accessUrl = accessUrl;
	}

	public int getAccessId() {
		return this.accessId;
	}

	public void setAccessId(int accessId) {
		this.accessId = accessId;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Date getAccessTime() {
		return this.accessTime;
	}

	public void setAccessTime(Date accessTime) {
		this.accessTime = accessTime;
	}

	public String getAccessUrl() {
		return this.accessUrl;
	}

	public void setAccessUrl(String accessUrl) {
		this.accessUrl = accessUrl;
	}

}