package com.ulic.ulweb.ulweb2.entity;

import java.sql.Clob;

import org.hibernate.lob.ClobImpl;

import com.ulic.ulweb.ulweb2.util.FormatUtil;

// default package

/**
 * ContentTmplEntity generated by MyEclipse Persistence Tools
 */

public class ContentTmplEntity implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int tmplId;

	private String tmplName;

	private Clob tmplContent;
	
	private String tmplContentString;


	// Property accessors



	public int getTmplId() {
		return this.tmplId;
	}

	public void setTmplId(int tmplId) {
		this.tmplId = tmplId;
	}

	public String getTmplName() {
		return this.tmplName;
	}

	public void setTmplName(String tmplName) {
		this.tmplName = tmplName;
	}

	
	
	public Clob getTmplContent() {
		return this.tmplContent;
	}
	
	public void setTmplContent(Clob tmplContent) {
		this.tmplContent = tmplContent;
	}
	

	public String getTmplContentString() {
		this.tmplContentString = FormatUtil.clob2String(this.tmplContent);
		return this.tmplContentString;
	}
	
	public void setTmplContentString(String tmplContentString) {
		this.tmplContentString = tmplContentString;
		this.tmplContent = new ClobImpl(this.tmplContentString);
	}



}