package com.ulic.ulweb.ulweb2.entity;

// default package

import java.sql.Clob;
import java.util.Date;
import java.util.List;

import org.hibernate.lob.ClobImpl;

import com.ulic.ulweb.ulweb2.util.FormatUtil;

/**
 * ContentEntity generated by MyEclipse Persistence Tools
 */

public class ContentEntity implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int contentId;

	private int columnId;

	private String contentName;

	private Clob content;
	
	private String contentString;

	private Date uploadTime;

	private String uploadUser;

	private String organId;

	private int isDelete;

	private int attachmentSum;

	private String keyWord;

	private Date updateTime;

	private int showOthersClass;

	private int showOrganClass;

	private int isQuickLink;

	private String documentNum;

	private String documentWord;

	private Date quickTime;

	private int haveContent;

	private int onIndex;

	private int displayType;

	private int quickTimeInt;

	private String subTitle;

	private String uploadDeptStr;

	private int uploadDeptInt;

	private int orderNum;
	
	private int isProcessing;
	
	private List attachmentList;

	// Property accessors

	public int getContentId() {
		return this.contentId;
	}

	public void setContentId(int contentId) {
		this.contentId = contentId;
	}

	public int getColumnId() {
		return this.columnId;
	}

	public void setColumnId(int columnId) {
		this.columnId = columnId;
	}

	public String getContentName() {
		return this.contentName;
	}

	public void setContentName(String contentName) {
		this.contentName = contentName;
	}

	public Clob getContent() {
		return this.content;
	}

	public void setContent(Clob content) {
		this.content = content;
		this.contentString = FormatUtil.clob2String(this.content);
	}

	public String getContentString() {
		return this.contentString;
	}
	
	public void setContentString(String contentString) {
		this.contentString = contentString;
		this.content = new ClobImpl(this.contentString);
	}
		
	
	public Date getUploadTime() {
		return this.uploadTime;
	}

	public void setUploadTime(Date uploadTime) {
		this.uploadTime = uploadTime;
	}

	public String getUploadUser() {
		return this.uploadUser;
	}

	public void setUploadUser(String uploadUser) {
		this.uploadUser = uploadUser;
	}

	public String getOrganId() {
		return this.organId;
	}

	public void setOrganId(String organId) {
		this.organId = organId;
	}

	public int getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(int isDelete) {
		this.isDelete = isDelete;
	}

	public int getAttachmentSum() {
		return this.attachmentSum;
	}

	public void setAttachmentSum(int attachmentSum) {
		this.attachmentSum = attachmentSum;
	}

	public String getKeyWord() {
		return this.keyWord;
	}

	public void setKeyWord(String keyWord) {
		this.keyWord = keyWord;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public int getShowOthersClass() {
		return this.showOthersClass;
	}

	public void setShowOthersClass(int showOthersClass) {
		this.showOthersClass = showOthersClass;
	}

	public int getShowOrganClass() {
		return this.showOrganClass;
	}

	public void setShowOrganClass(int showOrganClass) {
		this.showOrganClass = showOrganClass;
	}

	public int getIsQuickLink() {
		return this.isQuickLink;
	}

	public void setIsQuickLink(int isQuickLink) {
		this.isQuickLink = isQuickLink;
	}

	public String getDocumentNum() {
		return this.documentNum;
	}

	public void setDocumentNum(String documentNum) {
		this.documentNum = documentNum;
	}

	public String getDocumentWord() {
		return this.documentWord;
	}

	public void setDocumentWord(String documentWord) {
		this.documentWord = documentWord;
	}

	public Date getQuickTime() {
		return this.quickTime;
	}

	public void setQuickTime(Date quickTime) {
		this.quickTime = quickTime;
	}

	public int getHaveContent() {
		return this.haveContent;
	}

	public void setHaveContent(int haveContent) {
		this.haveContent = haveContent;
	}

	public int getOnIndex() {
		return this.onIndex;
	}

	public void setOnIndex(int onIndex) {
		this.onIndex = onIndex;
	}

	public int getDisplayType() {
		return this.displayType;
	}

	public void setDisplayType(int displayType) {
		this.displayType = displayType;
	}

	public int getQuickTimeInt() {
		return this.quickTimeInt;
	}

	public void setQuickTimeInt(int quickTimeInt) {
		this.quickTimeInt = quickTimeInt;
	}

	public String getSubTitle() {
		return this.subTitle;
	}

	public void setSubTitle(String subTitle) {
		this.subTitle = subTitle;
	}

	public String getUploadDeptStr() {
		return this.uploadDeptStr;
	}

	public void setUploadDeptStr(String uploadDeptStr) {
		this.uploadDeptStr = uploadDeptStr;
	}

	public int getUploadDeptInt() {
		return this.uploadDeptInt;
	}

	public void setUploadDeptInt(int uploadDeptInt) {
		this.uploadDeptInt = uploadDeptInt;
	}

	public int getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(int orderNum) {
		this.orderNum = orderNum;
	}

	public List getAttachmentList() {
		return attachmentList;
	}

	public void setAttachmentList(List attachmentList) {
		this.attachmentList = attachmentList;
	}

	public int getIsProcessing() {
		return isProcessing;
	}

	public void setIsProcessing(int isProcessing) {
		this.isProcessing = isProcessing;
	}
	
	private static String titleColor[] = {"#000000","#ffffff","#000000","#0066ff","#009900","#00dddd","#ffccff","#9900cc","#ffcc00","#ff0000"};
	
	public String getContentColor() {
		return titleColor[displayType];
	}
	
	public String getContentNameLink() {
		StringBuffer sb = new StringBuffer();
		sb.append("<a href='show.do?c=" + contentId);
		if (haveContent == 0) {
			sb.append("&a=1");
		}
		sb.append("' target='_blank' style='color: " + getContentColor() + "'>"
				+ contentName + "</a>&nbsp;&nbsp;");
		
		return sb.toString();
	}
	
	public String getAttachmentLink() {
		StringBuffer sb = new StringBuffer();
		if (haveContent == 0) {
			for (int i = 1 ; i <= attachmentSum - 1; i++) {
				sb.append("<a href='show.do?c=" + contentId + "&a=" + (i + 1)
						+ "' target='_blank'>附件" + i + "</a>&nbsp;&nbsp;");
			}
		} else {
			for (int i = 1 ; i <= attachmentSum; i++) {
				sb.append("<a href='show.do?c=" + contentId + "&a=" + i
						+ "' target='_blank'>附件" + i + "</a>&nbsp;&nbsp;");
			}
		}

		return sb.toString();
	}
	
	public String getNew() {
		StringBuffer sb = new StringBuffer();
		Date dt = new Date();
		dt.setDate(dt.getDate() - 3);
		if (this.uploadTime.after(dt)) { 
			sb.append("<img src='images/new.gif'>");
		}
		
		return sb.toString();
	}

}