package com.ulic.ulweb.ulweb2.entity;

/**
 * DeptEntity generated by MyEclipse Persistence Tools
 */

public class DeptEntity implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String deptId;

	private String deptName;

	private int deptModel;

	private int contentTmplId;

	private String contentTmplName;

	// Property accessors

	public String getContentTmplName() {
		return contentTmplName;
	}

	public void setContentTmplName(String contentTmplName) {
		this.contentTmplName = contentTmplName;
	}

	public String getDeptId() {
		return this.deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public int getDeptModel() {
		return this.deptModel;
	}

	public void setDeptModel(int deptModel) {
		this.deptModel = deptModel;
	}

	public int getContentTmplId() {
		return this.contentTmplId;
	}

	public void setContentTmplId(int contentTmplId) {
		this.contentTmplId = contentTmplId;
	}

}