package com.ulic.ulweb.ulweb2.entity;

import java.sql.Clob;
import java.util.Date;

import org.hibernate.lob.ClobImpl;

import com.ulic.ulweb.ulweb2.util.FormatUtil;

/**
 * UlMail generated by MyEclipse Persistence Tools
 */

public class MailEntity implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int mailId;

	private String mailSubject;

	private Clob mailBody;
	
	private String mailBodyString;

	private String mailTo;

	private String mailCc;

	private String mailBcc;

	private String mailFrom;

	private Date sendTime;

	private int isSuccess;

	private int contentId;

	private int attachmentId;

	private String mailDesc;

	public int getAttachmentId() {
		return attachmentId;
	}

	public void setAttachmentId(int attachmentId) {
		this.attachmentId = attachmentId;
	}

	public int getContentId() {
		return contentId;
	}

	public void setContentId(int contentId) {
		this.contentId = contentId;
	}

	public int getIsSuccess() {
		return isSuccess;
	}

	public void setIsSuccess(int isSuccess) {
		this.isSuccess = isSuccess;
	}

	public String getMailBcc() {
		return mailBcc;
	}

	public void setMailBcc(String mailBcc) {
		this.mailBcc = mailBcc;
	}

	public Clob getMailBody() {
		return mailBody;
	}

	public void setMailBody(Clob mailBody) {
		this.mailBody = mailBody;
	}
	
	public String getMailBodyString() {
		this.mailBodyString = FormatUtil.clob2String(this.mailBody);
		return mailBodyString;
	}

	public void setMailBodyString(String mailBodyString) {
		this.mailBodyString = mailBodyString;
		this.mailBody = new ClobImpl(this.mailBodyString);
	}

	public String getMailCc() {
		return mailCc;
	}

	public void setMailCc(String mailCc) {
		this.mailCc = mailCc;
	}

	public String getMailDesc() {
		return mailDesc;
	}

	public void setMailDesc(String mailDesc) {
		this.mailDesc = mailDesc;
	}

	public String getMailFrom() {
		return mailFrom;
	}

	public void setMailFrom(String mailFrom) {
		this.mailFrom = mailFrom;
	}

	public int getMailId() {
		return mailId;
	}

	public void setMailId(int mailId) {
		this.mailId = mailId;
	}

	public String getMailSubject() {
		return mailSubject;
	}

	public void setMailSubject(String mailSubject) {
		this.mailSubject = mailSubject;
	}

	public String getMailTo() {
		return mailTo;
	}

	public void setMailTo(String mailTo) {
		this.mailTo = mailTo;
	}

	public Date getSendTime() {
		return sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

}